const City = [
    {
        name: 'Calgary',
        population: 1640000,
        facilities: 7,
        info: 'The largest city in Alberta and the largest metro area within the three Prairie Provinces region.',
        img: 'https://images.pexels.com/photos/12294487/pexels-photo-12294487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        route: '/locations/calgary',
    },
    {
        name: 'Airdrie',
        population: 80649,
        facilities: 1,
        info: 'Fifth largest city in Alberta, Airdrie was first established as a railway siding in 1889 during the construction of the Calgary and Edmonton Railway ',
        img: 'https://www.airdrie.ca/documents/IGA__Airdrie_Urgent_Care_building_with_doctor_icon.jpg',
        route: '/facilities/airdrieCommunityHealthCentre',
    },
    {
        name: 'Cochrane',
        population: 35825,
        facilities: 1,
        info: 'Cochrane is a town in the Calgary Metropolitan Region of Alberta, Canada.',
        img: 'https://dht7q8fif4gks.cloudfront.net/2021-11/cochranesign2%20%281%29.jpg',
        route: '/facilities/cochraneCommunityHealthCentre',
    },
    {
        name: 'Okotoks',
        population: 36338,
        facilities: 1,
        info: 'Okotoks is a town in the Calgary Region of Alberta, Canada. Okotoks has emerged as a bedroom community of Calgary.',
        img: 'https://d3d0lqu00lnqvz.cloudfront.net/media/media/3b6d7b08-6a6e-43bd-adc4-3966fa1a210c.jpg',
        route: '/facilities/okotoksHealthAndWellnessCentre',
    },
    {
        name: 'Edmonton',
        population: 1544000,
        facilities: 6,
        info: 'The capital city of the Canadian province of Alberta. Edmonton is situated on the North Saskatchewan River.',
        img: 'https://images.pexels.com/photos/280490/pexels-photo-280490.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        route: '/locations/edmonton',
    },
    {
        name: 'Devon',
        population: 6689,
        facilities: 1,
        info: 'Devon owes its existence to one of the largest oil discoveries in the world.',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Devonian_Japanese_Garden.jpg/640px-Devonian_Japanese_Garden.jpg',
        route: '/facilities/devonGeneralHospital',
    },
    {
        name: 'Fort Saskatchewan',
        population: 28045,
        facilities: 1,
        info: 'Fort Saskatchewan is a city along the North Saskatchewan River in Alberta, Canada.',
        img: 'https://i0.wp.com/www.davidmurrayarchitect.ca/wp-content/uploads/2016/03/Fort-Saskatchewan-CN-Station.jpg',
        route: '/facilities/devonGeneralHospital',
    },
    {
        name: 'Leduc',
        population: 36060,
        facilities: 1,
        info: 'The City of Leduc is a growing, dynamic city in the heart of Canadas economic engine.',
        img: 'https://onthisspot.ca/app/leduc/big/1909mainn.jpg',
        route: '/facilities/leducCommunityHospital',
    },
    {
        name: 'Sherwood Park',
        population: 72017,
        facilities: 1,
        info: 'Sherwood Park is a large hamlet in Alberta, Canada within Strathcona County that is recognized as an urban service area.',
        img: 'https://lachanceteam.com/wp-content/uploads/2018/02/content_Sherwood_Flickr.jpg',
        route: '/facilities/strathconaCommunityHospital',
    },
    {
        name: 'St. Albert',
        population: 70422,
        facilities: 1,
        info: 'St. Albert is a city in Alberta on the Sturgeon River northwest of the City of Edmonton. It was originally settled as a Métis community.',
        img: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Downtown_clocktower_St._Albert_Alberta.jpg',
        route: '/facilities/sturgeonCommunityHospital',
    },
    {
        name: 'Stony Plain',
        population: 20702,
        facilities: 1,
        info: 'Stony Plain is a town in the Edmonton Metropolitan Region of Alberta, Canada that is surrounded by Parkland County',
        img: 'https://smartcdn.gprod.postmedia.digital/nexus/wp-content/uploads/2022/05/0527-sb-downtown-scaled.jpg',
        route: '/facilities/westViewHealthCentre',
    },
    {
        name: 'Red Deer',
        population: 109489,
        facilities: 1,
        info: 'Key industries include health care, retail trade, construction, oil and gas, hospitality, manufacturing and education.',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Red_Deer_-_Aerial_-_downtown_bridges.jpg/1920px-Red_Deer_-_Aerial_-_downtown_bridges.jpg',
        route: '/facilities/redDeerRegionalHospital',
    },
    {
        name: 'Grande Prairie',
        population: 75414,
        facilities: 1,
        info: 'City in northwest Alberta, Canada within the southern portion of an area known as Peace River Country.',
        img: 'https://upload.wikimedia.org/wikipedia/commons/6/68/GPSkyline.jpg',
        route: '/facilities/grandePrairieRegionalHospital',
    },
    {
        name: 'Lethbridge',
        population: 106550,
        facilities: 1,
        info: 'Lethbridge is the commercial, financial, transportation and industrial centre of southern Alberta.',
        img: 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Downtown_Lethbridge_Skyline.jpg',
        route: '/facilities/chinookRegionalHospital',
    },
    {
        name: 'Medicine Hat',
        population: 68116,
        facilities: 1,
        info: 'Medicine Hat is the sunniest place in Canada according to Environment and Climate Change Canada',
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Medicine_Hat_College_View.jpg/1920px-Medicine_Hat_College_View.jpg',
        route: '/facilities/medicineHatRegionalHospital',
    },


    
]

export default City;