const Hospitals = [
    {
        municipality: 'CalgaryER',
        key: 'ACH',
        name: 'Alberta Childrens Hospital',
        info: 'This facility provides a range of healthcare services for children up to 18 years old.',
        img: 'https://childrenshospitals.ca/wp-content/uploads/2019/03/achf2.jpg',
        route: 'albertaChildrensHospital',
        aboutInfo: 'Alberta Childrens Hospital in Calgary partnering together with children, youth, families, staff and physicians to provide the utmost in excellent care. We treat each other with respect, listen to one another, share ideas and information, ask and answer questions, create a safe environment for interaction, and make decisions together.',
        contactInfo: {
            adress:{
                street: '28 Oki Drive NW',
                city: 'Calgary, Alberta',
                zip: 'T3B 6A8',
            },
            phone: '403-955-7211',
            website: 'https://www.ahs.ca/ach',
        },
    },
    {
        municipality: 'CalgaryER',
        key: 'FMC',
        name: 'Foothills Medical Centre',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://i.cbc.ca/1.4868516.1679528199!/fileImage/httpImage/image.JPG_gen/derivatives/16x9_780/foothills-medical-centre-hospital.JPG',
        route: 'foothillsMedicalCentre',
        aboutInfo: 'The Foothills Medical Centre (FMC), one of Canadas largest hospitals, provides advanced healthcare services to more than two million people.',
        contactInfo: {
            adress:{
                street: '1403 29 Street NW',
                city: 'Calgary, Alberta',
                zip: 'T2N 2T9',
            },
            phone: '403-944-1110',
            website: 'https://www.ahs.ca/fmc',
        },
       
    },
    {
        municipality: 'CalgaryER',
        key: 'PLC',
        name: 'Peter Lougheed Centre',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://i.cbc.ca/1.5840643.1607971692!/cumulusImage/httpImage/image.jpg_gen/derivatives/16x9_780/peter-lougheed-centre-calgary-drone-shots.jpg',
        route: 'peterLougheedCentre',
        aboutInfo: 'A full-service, acute care hospital offering care to more than 150,000 patients annually. Peter Lougheed Centre is southern Alberta centre of excellence for hematology, respiratory, vascular surgery and addictions and mental health.',
        contactInfo: {
            adress:{
                street: '3500 26 Avenue NE',
                city: 'Calgary, Alberta',
                zip: 'T1Y 6J4',
            },
            phone: '403-943-4555',
            website: 'https://www.ahs.ca/plc',
        },
       
    },
    {
        municipality: 'CalgaryER',
        key: 'RGH',
        name: 'Rockyview General Hospital',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department',
        img: 'https://i.cbc.ca/1.5840633.1655256865!/cumulusImage/httpImage/image.jpg_gen/derivatives/16x9_780/rockyview-general-hospital-calgary-drone-shots.jpg',
        route: 'rockyviewGeneralHospital',
        aboutInfo: 'Caring for nearly 220,000 patients every year, Rockyview General Hospital (RGH) offers a full range of acute and outpatient care, including Emergency, Critical Care, Urology and Ophthalmology.',
        contactInfo: {
            adress:{
                street: '7007 14 Street SW',
                city: 'Calgary, Alberta',
                zip: 'T2V 1P9',
            },
            phone: '403-943-3000',
            website: 'https://www.ahs.ca/rgh',
        },
        
    },
    {
        municipality: 'CalgaryER',
        key: 'SHC',
        name: 'South Health Campus',
        info: 'South Health Campus (SHC) is a full service 272-bed hospital, supporting over 19,000 inpatients per year',
        img: 'https://kasian.com/wp-content/uploads/2022/08/AB-Health-Services-project.jpg',
        route: 'southHealthCampus',
        aboutInfo: 'The South Health Campus (SHC) is more than a place to treat illness and disease. By inspiring a wellness mindset, we focus on supporting, encouraging and assisting people along their health and wellness journey.',
        contactInfo: {
            adress:{
                street: '4448 Front Street SE',
                city: 'Calgary, Alberta',
                zip: 'T3M 1M4',
            },
            phone: '403-956-1111',
            website: 'https://www.ahs.ca/shc',
        },
        
    },
    {
        municipality: 'CalgaryUC',
        key: 'ACHC',
        name: 'Airdrie Community Health Centre',
        info: 'Providing a wide range of health services to residents and families living in and around Airdrie.',
        img: 'https://content.betterimpact.com/files/agency/14020/airdrie-urgent-care.png',
        route: 'airdrieCommunityHealthCentre',
        aboutInfo: 'The Airdrie Community Health Centre, providing a wide range of health services to residents and families living in and around Airdrie.',
        contactInfo: {
            adress:{
                street: '604 Main Street S',
                city: 'Airdrie, Alberta',
                zip: 'T4B 3K7',
            },
            phone: '403-912-8400',
            website: 'https://www.ahs.ca/achc',
        },
    },
    {
        municipality: 'CalgaryUC',
        key: 'CCHC',
        name: 'Cochrane Community Health Centre',
        info: 'This facility is wheelchair accessible',
        img: 'https://dht7q8fif4gks.cloudfront.net/2019-11/toby%20award.png',
        route: 'cochraneCommunityHealthCentre',
        aboutInfo: 'Provides a wide range of health services that may include prenatal / postpartum services, health promotion / disease and injury prevention services, well child services, immunizations, communicable disease control, and school health services.',
        contactInfo: {
            adress:{
                street: '60 Grande Boulevard',
                city: 'Cochrane, Alberta',
                zip: 'T4C 0S4',
            },
            phone: '403-851-6000',
            website: 'not provided by AHS',
        },
    },
    {
        municipality: 'CalgaryUC',
        key: 'SMCHC',
        name: 'Sheldon M. Chumir Health Centre',
        info: 'This facility provides 24/7 care for people with injuries or illnesses that are not life threatening. Other healthcare services have limited hours.',
        img: 'https://commissioning.ca/wp-content/uploads/2020/12/ctc_front.jpg',
        route: 'sheldonMChumirCentre',
        aboutInfo: 'Medical care for complex or urgent health concerns. Urgent care services are for people who have unexpected but non-life-threatening health concerns that usually require same-day treatment.',
        contactInfo: {
            adress:{
                street: '1213 4 Street SW',
                city: 'Calgary, Alberta',
                zip: 'T2R 0X7',
            },
            phone: '403-955-6200',
            website: 'not provided by AHS',
        },
    },
    {
        municipality: 'CalgaryUC',
        key: 'SCHC',
        name: 'South Calgary Health Centre',
        info: 'This facility is wheelchair accessible and has an elevator on site.',
        img: 'https://i.cbc.ca/1.6539458.1659491252!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_780/south-calgary-health-centre.jpg',
        route: 'southCalgaryHealthCentre',
        aboutInfo: 'Medical care for complex or urgent health concerns. Urgent care services are for people who have unexpected but non-life-threatening health concerns that usually require same-day treatment.',
        contactInfo: {
            adress:{
                street: '31 Sunpark Plaza SE',
                city: 'Calgary, Alberta',
                zip: 'T2X 3W5',
            },
            phone: '403-943-9300',
            website: 'not provided by AHS',
        },
    },
    {
        municipality: 'CalgaryUC',
        key: 'OHWC',
        name: 'Okotoks Health and Wellness Centre',
        info: 'This facility is wheelchair accessible.',
        img: 'https://www.okotoks.ca/sites/default/files/styles/banner_inside/public/pictures/banner-images/family-resource-centre_0.jpg?itok=bhGo86hg',
        route: 'okotoksHealthAndWellnessCentre',
        aboutInfo: 'The Okotoks Health and Wellness Centre houses a variety of services, including the Urgent Care Centre, as well as the Okotoks Family Resource Centre.',
        contactInfo: {
            adress:{
                street: '11 Cimarron Common',
                city: 'Okotoks, Alberta',
                zip: 'T1S 2E9',
            },
            phone: '403-995-2600',
            website: 'not provided by AHS',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'DGH',
        name: 'Devon General Hospital',
        info: 'This facility provides a range of healthcare services including an emergency department with limited hours.',
        img: 'https://smartcdn.gprod.postmedia.digital/nexus/wp-content/uploads/2020/04/0424-dd-hospital2.jpg',
        route: 'devonGeneralHospital',
        aboutInfo: 'The Devon General Hospital, providing a range of acute and long-term care, including 24-hour emergency services, home care services, laboratory services, diagnostic imaging and public health.',
        contactInfo: {
            adress:{
                street: '101 Erie Street S',
                city: 'Devon, Alberta',
                zip: 'T9G 1A6',
            },
            phone: '780-342-7000',
            website: 'https://www.ahs.ca/devon',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'FSCH',
        name: 'Fort Sask Community Hospital',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://mclpower.com/wp-content/uploads/2018/01/Fort14.jpg',
        route: 'fortSaskCommunityHospital',
        aboutInfo: 'The Fort Saskatchewan Community Hospital is an acute care facility, located northeast of Edmonton, offering a range of acute and outpatient care .',
        contactInfo: {
            adress:{
                street: '9401 86 Avenue',
                city: 'Fort Saskatchewan, Alberta',
                zip: 'T8L 0C6',
            },
            phone: '780-998-2256',
            website: 'https://www.ahs.ca/fortsask',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'GNCH',
        name: 'Grey Nuns Community Hospital',
        info: 'This Covenant Health facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://upload.wikimedia.org/wikipedia/commons/3/35/2008-10-30_Grey_Nuns_Community_Hospital.jpg',
        route: 'greyNunsCommunityHospital',
        aboutInfo: 'The Grey Nuns Community Hospital is a full-service acute care facility. We have served the people of southeast Edmonton since 1988.',
        contactInfo: {
            adress:{
                street: '1100 Youville Drive NW',
                city: 'Edmonton, Alberta',
                zip: 'T6L 5X8',
            },
            phone: '780-735-7000',
            website: 'not provided by AHS',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'LCH',
        name: 'Leduc Community Hospital',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Leduc_Community_Hospital.jpg',
        route: 'leducCommunityHospital',
        aboutInfo: 'The Leduc Community hospital, located 20 kilometers south of Edmonton, provides a range of acute and outpatient care including 24-hour emergency services.',
        contactInfo: {
            adress:{
                street: '4210 48 Street',
                city: 'Leduc, Alberta',
                zip: 'T9E 5Z3',
            },
            phone: '780-986-7711',
            website: 'https://www.ahs.ca/leduc',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'MCH',
        name: 'Misericordia Community Hospital',
        info: 'This Covenant Health facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://neoslibraries.ca/wp-content/uploads/2/files/sites/2/2023/01/edm10870907-e1675377704311.jpg',
        route: 'misericordiaCommunityHospital',
        aboutInfo: 'The Misericordia Community Hospital is a full-service acute care facility. We have served the people of northwest Edmonton on our current site since 1969.',
        contactInfo: {
            adress:{
                street: '16940 87 Avenue',
                city: 'Edmonton, Alberta',
                zip: 'T5R 4H5',
            },
            phone: '780-735-2000',
            website: 'not provided by AHS',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'NECHC',
        name: 'Northeast Community Health Centre',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://www.albertahealthservices.ca/assets/hospitals/nechc/nechc-image-1.jpg',
        route: 'northeastCommunityHealthCentre',
        aboutInfo: 'The Northeast Community Health Centre, located in northeast Edmonton, offers a range of outpatient and ambulatory care including 24-hour emergency services.',
        contactInfo: {
            adress:{
                street: '14007 50 Street NW',
                city: 'Edmonton, Alberta',
                zip: 'T5A 5E4',
            },
            phone: '780-342-4000',
            website: 'https://www.ahs.ca/nechc',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'RAH',
        name: 'Royal Alexandra Hospital',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department',
        img: 'https://i.cbc.ca/1.5854684.1608839761!/cumulusImage/httpImage/royal-alexandra-hospital.jpg',
        route: 'royalAlexandraHospital',
        aboutInfo: 'Named for Queen Alexandra, the Royal Alexandra Hospital (RAH) is located in Edmontons inner-city and serves a diverse community of patients from Edmonton, Alberta, the Territories, and Western Canada.',
        contactInfo: {
            adress:{
                street: '10240 Kingsway NW',
                city: 'Edmonton, Alberta',
                zip: 'T5H 3V9',
            },
            phone: '780-735-4111',
            website: 'https://www.ahs.ca/rah',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'SCH',
        name: 'Stollery Childrens Hospital',
        info: 'This facility provides a range of healthcare services for children including a 24/7 emergency department.',
        img: 'https://edmonton.citynews.ca/wp-content/blogs.dir/sites/15/Stoller-y-e1671580082700.jpg',
        route: 'stolleryChildrensHospital',
        aboutInfo: 'The Stollery Childrens Hospital in Edmonton, Alberta, is a full-service pediatric hospital and centre for complex pediatric care and research established in 2001',
        contactInfo: {
            adress:{
                street: '8440 112 Street',
                city: 'Edmonton, Alberta',
                zip: 'T6G 2B7',
            },
            phone: '780-407-8822',
            website: 'https://www.ahs.ca/stollery',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'STRTHN',
        name: 'Strathcona Community Hospital',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://cdn.canada247.info/assets/uploads/d84d8752187e82cc9f28c85cfb10db75_-alberta-division-no-11-strathcona-county-sherwood-park-strathcona-community-hospitalhtml.jpg',
        route: 'srathconaCommunityHospital',
        aboutInfo: 'The Strathcona Community Hospital in Sherwood Park is an innovative facility, delivering primary health care, combined with community-based services and a 24-hour emergency department supported by on-site diagnostic services.',
        contactInfo: {
            adress:{
                street: '9000 Emerald Drive',
                city: 'Sherwood Park, Alberta',
                zip: 'T8H 0J3',
            },
            phone: '780-449-5380',
            website: 'https://www.ahs.ca/strathcona',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'STRGN',
        name: 'Sturgeon Community Hospital',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://beta.ctvnews.ca/content/ctvnews/en/local/edmonton/2021/6/6/1_5458624/jcr%3acontent/root/responsivegrid/image.coreimg.png/1623012759904.png',
        route: 'sturgeonCommunityHospital',
        aboutInfo: 'Located just northwest of Edmonton, the Sturgeon Community Hospital is a 167-bed hospital that provides a wide variety of health services to the community of St. Albert and surrounding area.',
        contactInfo: {
            adress:{
                street: '201 Boudreau Road',
                city: 'St. Albert, Alberta',
                zip: 'T8N 6C4',
            },
            phone: '780-418-820',
            website: 'not provided by AHS',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'UOAH',
        name: 'University of Alberta Hospital',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://www.albertahealthservices.ca/assets/hospitals/uah/uah-image-1.jpg',
        route: 'universityOfAlbertaHospital',
        aboutInfo: 'The University of Alberta Hospital (UAH) is one of Canadas leading academic health sciences centres with a reputation for research, innovation, education, and patient-centred care.',
        contactInfo: {
            adress:{
                street: '8440 112 Street NW',
                city: 'Edmonton, Alberta',
                zip: 'T6G 2B7',
            },
            phone: '780-407-8822',
            website: 'https://www.ahs.ca/uah',
        },
    },
    {
        municipality: 'Edmonton',
        key: 'WVHC',
        name: 'WestView Health Centre',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://images.squarespace-cdn.com/content/v1/5c6ee576c46f6d403daf7517/1560452141707-2JP6R6TGDNBVXVWIEH3F/Health+Centre+043.jpg',
        route: 'westViewHealthCentre',
        aboutInfo: 'WestView Health Centre is a medical facility with a 24-hour emergency department located in Stony Plain, Alberta that is operated by Alberta Health Services. It is a 68-bed facility and features hospice care within its continuing care unit.',
        contactInfo: {
            adress:{
                street: '4405 South Park Driv',
                city: 'Stony Plain, Alberta',
                zip: 'T7Z 2M7',
            },
            phone: '780-968-3600',
            website: 'not provided by AHS',
        },
    },
    {
        municipality: 'Red Deer',
        key: 'RDRH',
        name: 'Red Deer Regional Hospital',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://www.reddeeradvocate.com/wp-content/uploads/2021/02/24344783_web1_191203-RDA-M-170208-RDA--RD-Hospital-.jpg',
        route: 'redDeerRegionalHospital',
        aboutInfo: 'The only regional referral centre for Central Zone, providing specialized healthcare services to over 450,000 people from Central Alberta spanning the area between Drumheller and Two Hills and from Saskatchewan to the Rocky Mountains.',
        contactInfo: {
            adress:{
                street: '3942 50A Avenue',
                city: 'Red Deer, Alberta',
                zip: 'T4N 4E7',
            },
            phone: '403-343-4422',
            website: 'https://www.ahs.ca/rdrhc',
        },
    },
    {
        municipality: 'Red Deer',
        key: 'IFHC',
        name: 'Innisfail Health Centre',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://www.albertahealthservices.ca/assets/images/facilities/1000315.jpg',
        route: 'innisfailHealthCentre',
        aboutInfo: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        contactInfo: {
            adress:{
                street: '5023 42 Street',
                city: 'Innisfail, Alberta',
                zip: 'T4G 1A9',
            },
            phone: '403-227-7800',
            website: 'https://www.ahs.ca/rdrhc',
        },
    },
    {
        municipality: 'Red Deer',
        key: 'LHACC',
        name: 'Lacombe Hospital and Care Centre',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department.',
        img: 'https://content.betterimpact.com/files/agency/14051/LHCC.JPG',
        route: 'lacombeHospitalAndCareCentre',
        aboutInfo: 'Emergency departments help you with your emergency health needs anytime day or night. They provide care for patients with major trauma, cardiac events, injuries, and general medical problems.',
        contactInfo: {
            adress:{
                street: '5430 47 Avenue',
                city: 'Lacombe, Alberta',
                zip: 'T4L 1G8',
            },
            phone: '403-786-496',
            website: 'https://www.ahs.ca/rdrhc',
        },
    },
    {
        municipality: 'Grande Prairie',
        key: 'GPRH',
        name: 'Grande Prairie Regional Hospital',
        info: 'This facility provides a range of healthcare services including a 24 / 7 emergency department. The Grande Prairie Cancer Centre is located within this facility.',
        img: 'https://www.albertahealthservices.ca/assets/hospitals/gprh/gprh-main-entrance.jpg',
        route: 'grandePrairieRegionalHospital',
        aboutInfo: 'An acute care facility in Grande Prairie, offering a wide-range of acute and outpatient care including 24-hour emergency, Grande Prairie Cancer Centre, surgery, mental health, intensive care, obstetrics and pediatrics.',
        contactInfo: {
            adress:{
                street: '11205 110 Street',
                city: 'Grande Prairie, Alberta',
                zip: 'T8V 4B',
            },
            phone: '825-412-4000',
            website: 'https://www.albertahealthservices.ca/gprh',
        },
    },
    {
        municipality: 'Lethbridge',
        key: 'CRH',
        name: 'Chinook Regional Hospital',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department. The Jack Ady Cancer Centre is located within this facility.',
        img: 'https://www.albertahealthservices.ca/assets/hospitals/crh/crh-night.jpg',
        route: 'chinookRegionalHospital',
        aboutInfo: 'Chinook Regional Hospital (CRH), offering a full range of healthcare services, including a 24/7 emergency department. Providing patient-centered care in south-western Alberta, including acute and subacute care, psychiatric, intensive care and neonatal intensive care',
        contactInfo: {
            adress:{
                street: '960 19 Street S',
                city: 'Lethbridge, Alberta',
                zip: 'T1J 1W5',
            },
            phone: '403-388-6111',
            website: 'https://www.ahs.ca/crh',
        },
    },
    {
        municipality: 'Medicine Hat',
        key: 'MHRH',
        name: 'Medicine Hat Regional Hospital',
        info: 'This facility provides a range of healthcare services including a 24/7 emergency department. The Margery E. Yuill Cancer Centre is located within this facility.',
        img: 'https://www.albertahealthservices.ca/assets/hospitals/mhrh/mhrh-image-home.jpg',
        route: 'medicineHatRegionalHospital',
        aboutInfo: 'Medicine Hat Regional Hospital (MHRH), providing patient-centered care in south-eastern Alberta. Offering a full range of healthcare services, including a 24/7 emergency department, acute care, intensive care and neonatal intensive care',
        contactInfo: {
            adress:{
                street: '666 5 Street SW',
                city: 'Medicine Hat, Alberta',
                zip: 'T1A 4H6',
            },
            phone: '403-529-8000',
            website: 'https://www.ahs.ca/mhrh',
        },
    },
    
]
export default Hospitals;



// {
//     municipality: '',
//     key: '',
//     name: '',
//     info: '',
//     img: '',
//     route: '',
//     aboutInfo: '',
//     contactInfo: {
//         adress:{
//             street: '',
//             city: '',
//             zip: '',
//         },
//         phone: '',
//         website: '',
//     },
// },