import './globals.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className='bg-cyan-50 p-1 m-1 max-w-7xl mx-auto'>
        
        {children}
      </body>
    </html>
  )
}
